### PR TITLE
ADS-B Aircraft Tracking support

### PR DESCRIPTION
**Pull request by aaronwmorris**

### CODE REVIEW

**Comment by Reble45** [comment]
Is There a chance we can get a module for this functionality? If not, can you please explain how to get detected aircraft to print on the Overlay as pictured in your discussion?

**Comment by aaronwmorris** [comment]
This overlay is already integrated into the latest release of indi-allsky.  You just need a Software Defined Radio USB dongle to receive the ADS-B broadcasts from aircraft.

https://github.com/aaronwmorris/indi-allsky/wiki/ADS%E2%80%90B-Aircraft-Tracking

**Comment by Reble45** [comment]
Overlay 1
Overlay 2
Not sure what I'm doing wrong then. The same goes for the Moon stuff, and the ISS stuff. I'm either missing something huge, or the overlay is semi-broken.

**Comment by Reble45** [comment]
Oh, hell, I feel like a doofus now. Sorry for the confusion.

**Comment by aaronwmorris** [comment]
No worries!

**Pull request merged**
