### PR TITLE
feat(boto_minio): add minio client for object storage

### PR DESCRIPTION
**Pull request by USA-RedDragon**
In order to use Minio, I needed to set a custom endpoint. I noticed this was commented out, so I went ahead and wired it up.

### CODE REVIEW

**Comment by USA-RedDragon** [comment]
Converting to draft. For the upload, the `endpoint_url` shouldn't contain the bucket name in the path, but the capture process sets the s3_prefix properly, so this patchset breaks uploads

**Comment by USA-RedDragon** [comment]
Fixed with 8c45e2239128bdfde1b136e1bc2b4bf9bd3fa2e3

**Comment by aaronwmorris** [comment]
What do you think about implementing this as a custom `S3 Utility` in the drop down and keep the origin AWS boto3 code as-is?

**Comment by USA-RedDragon** [comment]
I've got zero issue with that, I'll pursue that direction. :)

**Comment by aaronwmorris** [comment]
Looks good to me, I will merge if you are ready.

**Comment by USA-RedDragon** [comment]
Just validated these changes, this one is good

**Pull request merged**
