### PR TITLE
docker: gunicorn: base on python:3.11 and shave 4gb off the image

### PR DESCRIPTION
**Pull request by USA-RedDragon**
This patch reduces the final size of the gunicorn image from a whopping 5.4GB down to 1.4GB. The Python dependencies alone take up 1.1GB (`/usr/local/lib/python3.11/site-packages`).

### CODE REVIEW

**Comment by aaronwmorris** [comment]
I think this image could be made even more simple.  indilib has not been a requirement for the gunicorn process for a while, I just never revisited this particular container.

libindi and pyindi-client should no longer be necessary.

**Comment by USA-RedDragon** [comment]
Not a huge impact, less than 100mb so `dive` is still reporting 1.4gb

**Comment by aaronwmorris** [comment]
One last change here... I have a reduced set of python requirements for the gunicorn image:  `requirements_latest_web.txt`

**Comment by aaronwmorris** [comment]
Looks good to me, I will merge if you are ready.

**Comment by USA-RedDragon** [comment]
Using the gunicorn-specific requirements brings the total image size to a nice round 1.0GB. This one should be good to ship

**Comment by USA-RedDragon** [comment]
Wait on this one, seems there's a missing dep

**Comment by USA-RedDragon** [comment]
Ok, tested with the patch above and it fires up properly now. This one should be good to go

**Pull request merged**
