### PR TITLE
allow maximum range of 24h for charts

### PR DESCRIPTION
**Pull request by jschmied**

### CODE REVIEW

**Comment by aaronwmorris** [comment]
If you can put the 45 minutes and 4 hour settings back in, I will get this merged.

**Comment by jschmied** [comment]
done

**Comment by aaronwmorris** [comment]
I've got to pull this into my dev branch to separate the forms for the chart view and the loop view.  I'll perform those updates and merge that back into main.

**Comment by aaronwmorris** [comment]
Okay, this is done.  Apparently, I shared the form for both the loop and chart views.  I did not want to allow 24 hours of history for the loop history because that could effectively DoS the web server by allowing 2000-3000 images to be downloaded at one time.

**Pull request merged**
